(() => {
  const C = window.SAMSON_CONFIG || { GOOGLE_SCRIPT_URL: "", LOW_STOCK_THRESHOLD: 10, CURRENCY: "₹" };
  const API_URL = String(C.GOOGLE_SCRIPT_URL || "").trim();
  if (sessionStorage.getItem("samson_admin_token") === "demo-session") sessionStorage.removeItem("samson_admin_token");
  const ORDERS_CACHE_KEY="samson_orders_cache";
  function readOrdersCache(){try{const value=JSON.parse(localStorage.getItem(ORDERS_CACHE_KEY)||"[]");return Array.isArray(value)?value:[];}catch(e){return [];}}
  const state = { products: [], orders: readOrdersCache(), selected: null, quantity: 1, step: 1, customer: {}, orderType: "Pickup", busy: false, error: "", toast: "", apiConnected: false };
  const root = document.getElementById("app");
  const $ = (s, el=document) => el.querySelector(s);
  const $$ = (s, el=document) => [...el.querySelectorAll(s)];
  const money = n => `${C.CURRENCY || "₹"}${Number(n || 0).toLocaleString("en-IN")}`;
  const esc = s => String(s ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;", "'":"&#39;"}[c]));
  const safeImage = url => url || "https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=900&q=80";
  const currency = n => Number(n || 0);
  const normalizeProduct = p => ({ id:String(p.id ?? p.ID ?? ""), name:String(p.name ?? p.NAME ?? ""), image:String(p.image ?? p.IMAGE ?? ""), stock:currency(p.stock ?? p.STOCK), price:currency(p.price ?? p.PRICE), enabled:p.enabled !== false });
  const normalizeOrder = o => ({ id:String(o.id ?? o.orderId ?? o[0] ?? ""), itemId:String(o.itemId ?? o.itemID ?? o[1] ?? ""), itemName:String(o.itemName ?? o.name ?? ""), image:String(o.image ?? ""), quantity:currency(o.quantity ?? o[2]), total:currency(o.total ?? o.totalAmount ?? o[3]), date:o.date ?? o.dateTime ?? o[4] ?? "", status:String(o.status ?? o.paymentStatus ?? o[5] ?? "Pending") });
  function api(action, payload={}) {
    if (!API_URL) return Promise.reject(new Error("Google Apps Script URL is not configured in config.js."));
    const base=API_URL;
    return new Promise((resolve,reject)=>{
      const cb=`samson_cb_${Date.now()}_${Math.random().toString(36).slice(2)}`;
      const script=document.createElement("script"); let timer;
      const cleanup=()=>{ delete window[cb]; script.remove(); clearTimeout(timer); };
      window[cb]=data=>{ cleanup(); if(data?.ok===false) reject(new Error(data.message||"Request failed")); else resolve(data?.data ?? data); };
      script.onerror=()=>{cleanup();reject(new Error("Network request failed"));};
      timer=setTimeout(()=>{cleanup();reject(new Error("Request timed out"));},18000);
      const params=new URLSearchParams({action,callback:cb,...payload});
      script.src=`${base}${base.includes("?")?"&":"?"}${params.toString()}`;
      document.head.appendChild(script);
    });
  }
  async function postApi(payload){
    if(!API_URL) throw new Error("Google Apps Script URL is not configured in config.js.");
    const response=await fetch(API_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(payload)});
    if(!response.ok) throw new Error("Order request failed.");
    const result=await response.json();
    if(!result?.success) throw new Error(result?.message||"Order request failed.");
    return result;
  }
  async function fetchOrders(){
    if(!API_URL) throw new Error("Google Apps Script URL is not configured in config.js.");
    const url=`${API_URL}${API_URL.includes("?")?"&":"?"}action=getOrders`;
    const response=await fetch(url);
    if(!response.ok) throw new Error("Orders request failed.");
    const result=await response.json();
    const orders=Array.isArray(result)?result:result?.orders||result?.data?.orders;
    if(!Array.isArray(orders)) throw new Error(result?.message||"Orders request failed.");
    return orders.map(raw=>{const order=normalizeOrder(raw),product=state.products.find(p=>p.id===order.itemId);return {...order,itemName:order.itemName||product?.name||order.itemId,image:order.image||product?.image||""};});
  }
  async function updatePaymentRemote(order,paymentStatus){
    const payload={action:"updatePayment",orderId:order.id,itemId:order.itemId,paymentStatus};
    await fetch(API_URL,{method:"POST",mode:"no-cors",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(payload)});
    for(let attempt=0;attempt<6;attempt++){
      await new Promise(resolve=>setTimeout(resolve,700));
      const orders=await fetchOrders();
      const updated=orders.find(item=>item.id===order.id);
      if(updated?.status===paymentStatus)return orders;
    }
    throw new Error("Payment status update was not confirmed by the Orders sheet.");
  }
  async function getPublicItems(){
    if(!API_URL) throw new Error("Google Apps Script URL is not configured in config.js.");
    async function request(action){
      const url=`${API_URL}${API_URL.includes("?")?"&":"?"}action=${encodeURIComponent(action)}`;
      const response=await fetch(url);
      if(!response.ok) throw new Error("Menu request failed.");
      return response.json();
    }
    let result=await request("getPublicItems");
    if(!result?.success) throw new Error(result?.message||"Menu request failed.");
    // Older deployments can return the API health response for an unknown action.
    // Fall back to the full item-list action supported by the supplied script.
    if(!Array.isArray(result.items)){
      result=await request("getItems");
      if(!result?.success) throw new Error(result?.message||"Menu request failed.");
    }
    const items=result.items;
    if(!Array.isArray(items)) throw new Error("Apps Script returned no item list. Redeploy the latest script and try again.");
    return items;
  }
  async function digest(value){const bytes=new TextEncoder().encode(value),hash=await crypto.subtle.digest("SHA-256",bytes);return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,"0")).join("");}
  function toast(message,error=false){ state.toast=message; const old=$(".toast");if(old)old.remove();const t=document.createElement("div");t.className=`toast${error?" error":""}`;t.textContent=message;document.body.appendChild(t);setTimeout(()=>t.remove(),3200); }
  function isAdmin(){return location.pathname.startsWith("/admin");}
  function navigate(path){ history.pushState({},"",path); state.error=""; render(); window.scrollTo(0,0); }
  window.addEventListener("popstate",()=>{render();});
  function header(){return `<header class="site-header"><a href="/" class="brand" data-nav="/">SAMSON CAFE<small>Good Coffee. Good Food. Good Moments.</small></a><div class="site-header-actions"><span class="header-note">Made fresh, just for you</span><a class="admin-entry" href="/admin/login" data-nav="/admin/login">ADMIN</a></div></header>`;}
  function availability(p){if(!p.enabled||p.stock<=0)return `<div class="availability out">OUT OF STOCK</div>`;return `<div class="availability ${p.stock<=Number(C.LOW_STOCK_THRESHOLD||10)?"low":""}">${p.stock} available</div>`;}
  function menuView(){
    const products=state.products.filter(p=>p.enabled);
    return `${header()}<main class="menu-wrap"><section class="menu-intro"><div><div class="eyebrow">From our kitchen</div><h1>Something lovely,<br class="mobile-break"> brewed for you.</h1><p>Your neighborhood pause, made with care.</p></div><div class="menu-meta">${products.length} menu ${products.length===1?"favorite":"favorites"}</div></section><section class="product-grid">${state.error?`<div class="error-state"><h2>Menu unavailable</h2><p>${esc(state.error)}</p><button class="button" data-action="reload">TRY AGAIN</button></div>`:products.length?products.map(p=>`<article class="product-card"><img class="product-image" src="${esc(safeImage(p.image))}" alt="${esc(p.name)}" loading="lazy" onerror="this.src='${safeImage("")}'"><div class="product-body"><div class="product-top"><h2 class="product-name">${esc(p.name)}</h2><div class="product-price">${money(p.price)}</div></div>${availability(p)}<button class="button full" data-buy="${esc(p.id)}" ${p.stock<=0?"disabled":""}>BUY NOW</button></div></article>`).join(""):`<div class="empty-state"><h2>A little quiet in the kitchen</h2><p>There are no menu items available right now.</p></div>`}</section></main>`;
  }
  function stepper(){return `<div class="stepper">${["Product","Details","Confirm"].map((x,i)=>`<div class="step-item ${state.step===i+1?"active":state.step>i+1?"done":""}"><span class="step-number">${state.step>i+1?"✓":i+1}</span><span>${x}</span></div>${i<2?'<span class="step-line"></span>':""}`).join("")}</div>`;}
  function checkoutView(){
    if(!state.selected){navigate("/");return "";} const p=state.selected,total=p.price*state.quantity;
    return `${header()}<main class="checkout-shell"><button class="back-link" data-action="back-menu">← &nbsp; Back to menu</button><div class="eyebrow">Quick order</div><h1 class="checkout-title">Your order</h1><section class="checkout-panel">${state.error?`<div class="notice">${esc(state.error)}</div>`:""}<div class="checkout-product"><img src="${esc(safeImage(p.image))}" alt="${esc(p.name)}" onerror="this.src='${safeImage("")}'"><div><div class="eyebrow">Order item</div><h2>${esc(p.name)}</h2><div class="item-id">Item ID · ${esc(p.id)}</div><div class="price-line">${money(p.price)} <span class="item-id">/ each</span></div><div class="stock-line">${p.stock} available</div><div class="qty-row"><span>Quantity</span><div class="qty-control"><button data-action="minus" aria-label="Decrease quantity">−</button><span>${state.quantity}</span><button data-action="plus" aria-label="Increase quantity" ${state.quantity>=p.stock?"disabled":""}>+</button></div></div><div class="total-box"><span>Total amount</span><strong>${money(total)}</strong></div></div></div><div class="panel-actions"><button class="button secondary" data-action="back-menu">BACK TO MENU</button><button class="button" data-action="place" ${state.busy||p.stock<1?"disabled":""}>${state.busy?"PLACING ORDER…":"PLACE ORDER"}</button></div></section></main>`;
  }
  function detailsForm(){const c=state.customer;return `<div class="eyebrow">Step 2 · Customer details</div><h2 class="product-name" style="margin:7px 0 20px">Where should we reach you?</h2><div class="form-grid"><div class="field"><label for="customer-name">Full name</label><input id="customer-name" autocomplete="name" value="${esc(c.name||"")}" placeholder="Your name" required></div><div class="field"><label for="customer-phone">Phone number</label><input id="customer-phone" inputmode="tel" autocomplete="tel" value="${esc(c.phone||"")}" placeholder="10-digit phone number" required></div><div class="field wide"><label for="customer-email">Email</label><input id="customer-email" type="email" autocomplete="email" value="${esc(c.email||"")}" placeholder="you@example.com" required></div><div class="field wide"><span class="group-label">Order type</span><div class="order-types">${["Pickup","Delivery"].map(t=>`<label class="choice ${state.orderType===t?"selected":""}"><input type="radio" name="order-type" value="${t}" ${state.orderType===t?"checked":""}>${t}</label>`).join("")}</div></div>${state.orderType==="Delivery"?`<div class="field wide"><label for="address">Address</label><input id="address" autocomplete="street-address" value="${esc(c.address||"")}" placeholder="House / street / area"></div><div class="field"><label for="landmark">Landmark</label><input id="landmark" value="${esc(c.landmark||"")}" placeholder="Nearby landmark"></div><div class="field"><label for="pincode">Pincode</label><input id="pincode" inputmode="numeric" value="${esc(c.pincode||"")}" placeholder="6-digit pincode"></div>`:""}<div class="field wide"><label for="note">Order note <span class="item-id">(optional)</span></label><textarea id="note" placeholder="Anything we should know?">${esc(c.note||"")}</textarea></div></div><div class="panel-actions"><button class="button secondary" data-action="step1">BACK</button><button class="button" data-action="save-details">CONTINUE</button></div>`;}
  function confirmForm(p,total){const c=state.customer;return `<div class="eyebrow">Step 3 · Confirm order</div><h2 class="product-name" style="margin:7px 0 20px">Everything look right?</h2><div class="summary-layout"><div><div class="summary-section"><h3>Your order</h3><div class="summary-line"><span>Product</span><strong>${esc(p.name)}</strong></div><div class="summary-line"><span>Item ID</span><strong>${esc(p.id)}</strong></div><div class="summary-line"><span>Quantity</span><strong>${state.quantity}</strong></div><div class="summary-line"><span>Price</span><strong>${money(p.price)} each</strong></div></div><div class="summary-section"><h3>Your details</h3><div class="summary-line"><span>Name</span><strong>${esc(c.name)}</strong></div><div class="summary-line"><span>Phone</span><strong>${esc(c.phone)}</strong></div><div class="summary-line"><span>Email</span><strong>${esc(c.email)}</strong></div></div><div class="summary-section"><h3>${esc(state.orderType)}</h3>${state.orderType==="Delivery"?`<div class="summary-line"><span>Address</span><strong>${esc(c.address)}</strong></div><div class="summary-line"><span>Landmark</span><strong>${esc(c.landmark||"—")}</strong></div><div class="summary-line"><span>Pincode</span><strong>${esc(c.pincode)}</strong></div>`:`<div class="summary-line"><span>Collect at Samson Cafe</span><strong>Pickup</strong></div>`}${c.note?`<div class="summary-line"><span>Note</span><strong>${esc(c.note)}</strong></div>`:""}</div></div><div class="summary-total"><div class="summary-line"><span>Payment status</span><span class="badge pending">Pending</span></div><div class="summary-line"><span>Total amount</span><strong>${money(total)}</strong></div><p class="item-id" style="margin:9px 0 0">Pay at ${state.orderType.toLowerCase()}.</p></div></div><div class="panel-actions"><button class="button secondary" data-action="step2">BACK</button><button class="button" data-action="place" ${state.busy?"disabled":""}>${state.busy?"PLACING ORDER…":"PLACE ORDER"}</button></div>`;}
  function successView(order){const p=order.product||state.selected;return `${header()}<main class="success-wrap"><div class="success-mark">✓</div><div class="eyebrow">A little happiness is on its way</div><h1 class="success-title">ORDER CONFIRMED</h1><p>Thank you for ordering from Samson Cafe.</p><div class="receipt"><div class="summary-line"><span>Order ID</span><strong>${esc(order.id)}</strong></div><div class="summary-line"><span>Item</span><strong>${esc(p?.name||order.itemId)} × ${order.quantity}</strong></div><div class="summary-line"><span>Total</span><strong>${money(order.total)}</strong></div><div class="summary-line"><span>Payment</span><span class="badge pending">${esc(order.status)}</span></div><div class="summary-line"><span>Date & time</span><strong>${esc(new Date(order.date).toLocaleString("en-IN"))}</strong></div></div><button class="button" data-action="back-menu">BACK TO MENU</button></main>`;}
  function adminLogin(){return `<main class="login-screen"><form class="login-card" id="login-form"><a class="brand" href="/" data-nav="/">SAMSON CAFE<small>CAFE MANAGEMENT</small></a><h1>Welcome back</h1><p>Sign in to manage your cafe.</p>${state.error?`<div class="notice">${esc(state.error)}</div>`:""}<div class="field"><label for="admin-password">Admin password</label><input id="admin-password" type="password" autocomplete="current-password" required placeholder="Enter admin password"></div><button class="button full">SIGN IN</button></form></main>`;}
  function adminNav(){const path=location.pathname;return `<aside class="admin-sidebar"><div class="nav-caption">WORKSPACE</div><nav class="admin-nav"><a class="${path==="/admin"?"active":""}" href="/admin" data-nav="/admin">Overview</a><a class="${path==="/admin/products"?"active":""}" href="/admin/products" data-nav="/admin/products">Products</a><a class="${path==="/admin/orders"?"active":""}" href="/admin/orders" data-nav="/admin/orders">Orders</a><a class="${path==="/admin/stock"?"active":""}" href="/admin/stock" data-nav="/admin/stock">Stock</a><a class="${path==="/admin/reports"?"active":""}" href="/admin/reports" data-nav="/admin/reports">Reports</a></nav></aside>`;}
  const isAuthed=()=>{const token=sessionStorage.getItem("samson_admin_token");return token&&token!=="demo-session"?token:"";};
  const apiAdmin=async(action,payload={})=>api(action,{...payload,adminToken:isAuthed()||""});
  function adminLayout(content){return `<div class="admin-shell"><header class="admin-top"><a href="/" class="brand" data-nav="/">SAMSON CAFE</a><div class="admin-top-right"><span class="api-state">${state.apiConnected?"Google Sheets connected":API_URL?"Google Sheets unavailable":"Apps Script URL missing"}</span><strong>Admin</strong><button class="text-button" data-action="logout">SIGN OUT</button></div></header><div class="admin-layout">${adminNav()}<main class="admin-content">${content}</main></div></div>`;}
  const stockBadge=p=>p.stock<=0?'<span class="badge out-stock">OUT OF STOCK</span>':p.stock<=Number(C.LOW_STOCK_THRESHOLD||10)?'<span class="badge low-stock">LOW STOCK</span>':'<span class="badge in-stock">IN STOCK</span>';
  function dashboard(){const products=state.products,orders=state.orders;const today=new Date().toDateString();const sales=orders.filter(o=>new Date(o.date).toDateString()===today&&o.status==="Paid").reduce((a,o)=>a+o.total,0);const pending=orders.filter(o=>o.status==="Pending").length,paid=orders.filter(o=>o.status==="Paid").length,low=products.filter(p=>p.stock<=Number(C.LOW_STOCK_THRESHOLD||10)).length;const stats=[["Total products",products.length,"In your menu"],["Total orders",orders.length,"All recorded orders"],["Pending orders",pending,"Awaiting payment"],["Paid orders",paid,"Payment received"],["Low stock",low,"At or below threshold"],["Today's sales",money(sales),"Paid orders today"]];return adminLayout(`<div class="admin-heading"><div><h1>Good day, cafe team</h1><p>Here’s how Samson Cafe is doing today.</p></div></div><section class="stats-grid">${stats.map(s=>`<article class="stat-card"><div class="stat-label">${s[0]}</div><div class="stat-value">${s[1]}</div><div class="stat-foot">${s[2]}</div></article>`).join("")}</section><section class="admin-card"><h2>Recent orders</h2>${orders.length?ordersTable(orders.slice(0,6),false):`<div class="empty-table">Your new orders will appear here.</div>`}<div style="margin-top:13px"><a class="text-button" href="/admin/orders" data-nav="/admin/orders">VIEW ALL ORDERS →</a></div></section>`);}
  function orderItemName(order){return order.itemName||state.products.find(p=>p.id===order.itemId)?.name||order.itemId;}
  function ordersTable(orders,actions=true){if(!orders.length)return `<div class="empty-table">No orders found. Use Refresh Orders to fetch the latest rows.</div>`;return `<div class="table-wrap"><table><thead><tr><th>Order ID</th><th>Item</th><th>Item ID</th><th>Quantity</th><th>Total</th><th>Date & time</th><th>Payment</th>${actions?"<th>Action</th>":""}</tr></thead><tbody>${orders.map(o=>`<tr><td><strong>${esc(o.id)}</strong></td><td>${esc(orderItemName(o))}</td><td>${esc(o.itemId)}</td><td>${o.quantity}</td><td>${money(o.total)}</td><td>${esc(formatDate(o.date))}</td><td><span class="badge ${o.status.toLowerCase()}">${esc(o.status)}</span></td>${actions?`<td><button class="text-button" data-order-details="${esc(o.id)}">VIEW</button></td>`:""}</tr>`).join("")}</tbody></table></div>`;}
  function formatDate(v){const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString("en-IN",{dateStyle:"medium",timeStyle:"short"});}
  function productsTable(products){return `<div class="table-wrap"><table><thead><tr><th>Product</th><th>ID</th><th>Stock</th><th>Price</th><th>Status</th><th>Menu</th><th>Action</th></tr></thead><tbody>${products.length?products.map(p=>`<tr><td><div class="table-product"><img src="${esc(safeImage(p.image))}" alt="" onerror="this.src='${safeImage("")}'"><strong>${esc(p.name)}</strong></div></td><td>${esc(p.id)}</td><td>${p.stock}</td><td>${money(p.price)}</td><td>${stockBadge(p)}</td><td><span class="badge ${p.enabled?"in-stock":"out-stock"}">${p.enabled?"ENABLED":"DISABLED"}</span></td><td><button class="text-button" data-edit="${esc(p.id)}">EDIT</button><button class="text-button" data-toggle="${esc(p.id)}">${p.enabled?"DISABLE":"ENABLE"}</button></td></tr>`).join(""):`<tr><td class="empty-table" colspan="7">No products yet.</td></tr>`}</tbody></table></div>`;}
  function productsPage(){return adminLayout(`<div class="admin-heading"><div><h1>Products</h1><p>Keep your menu, pricing, and availability up to date.</p></div><button class="admin-button" data-action="add-product">+ &nbsp; ADD PRODUCT</button></div><section class="admin-card"><div class="toolbar"><input type="search" placeholder="Search products…" data-search="products"><select data-filter="product-stock"><option value="">All stock levels</option><option value="low">Low stock</option><option value="out">Out of stock</option></select></div><div id="products-table">${productsTable(state.products)}</div></section>`);}
  function ordersPage(){return adminLayout(`<div class="admin-heading"><div><h1>Orders</h1><p>Orders refresh automatically every minute.</p></div><button class="admin-button" data-action="refresh-orders">REFRESH ORDERS</button></div><section class="admin-card"><div class="toolbar"><input type="search" placeholder="Search order or item ID…" data-search="orders"><select data-filter="status"><option value="">All payment statuses</option><option>Pending</option><option>Paid</option></select><input type="date" data-filter="date" aria-label="Filter by date"><select data-filter="sort"><option value="newest">Newest first</option><option value="oldest">Oldest first</option></select></div><div id="orders-table">${ordersTable(state.orders)}</div></section>`);}
  function stockPage(){const rows=state.products;return adminLayout(`<div class="admin-heading"><div><h1>Stock</h1><p>Low stock alert threshold: ${Number(C.LOW_STOCK_THRESHOLD||10)} items.</p></div></div><section class="admin-card"><div class="toolbar"><input type="search" placeholder="Search products…" data-search="stock"><select data-filter="stock-level"><option value="">All stock statuses</option><option value="low">Low stock</option><option value="out">Out of stock</option><option value="in">In stock</option></select></div><div class="table-wrap" id="stock-table">${stockTable(rows)}</div></section>`);}
  function stockTable(rows){return `<table><thead><tr><th>Product</th><th>Item ID</th><th>Current stock</th><th>Price</th><th>Stock status</th><th>Action</th></tr></thead><tbody>${rows.length?rows.map(p=>`<tr><td><div class="table-product"><img src="${esc(safeImage(p.image))}" alt="" onerror="this.src='${safeImage("")}'"><strong>${esc(p.name)}</strong></div></td><td>${esc(p.id)}</td><td><strong>${p.stock}</strong></td><td>${money(p.price)}</td><td>${stockBadge(p)}</td><td><button class="text-button" data-stock="${esc(p.id)}">UPDATE STOCK</button></td></tr>`).join(""):`<tr><td class="empty-table" colspan="6">No products found.</td></tr>`}</tbody></table>`;}
  function reportsPage(){const paid=state.orders.filter(o=>o.status==="Paid");const byDay={};paid.forEach(o=>{const key=new Date(o.date).toLocaleDateString("en-IN");byDay[key]=(byDay[key]||0)+o.total;});return adminLayout(`<div class="admin-heading"><div><h1>Reports</h1><p>Sales from orders marked Paid in your Orders sheet.</p></div></div><section class="stats-grid"><article class="stat-card"><div class="stat-label">Paid order total</div><div class="stat-value">${paid.length}</div><div class="stat-foot">Recorded paid orders</div></article><article class="stat-card"><div class="stat-label">Paid sales</div><div class="stat-value">${money(paid.reduce((a,o)=>a+o.total,0))}</div><div class="stat-foot">Across all recorded dates</div></article><article class="stat-card"><div class="stat-label">Average paid order</div><div class="stat-value">${money(paid.length?paid.reduce((a,o)=>a+o.total,0)/paid.length:0)}</div><div class="stat-foot">Paid sales per order</div></article></section><section class="admin-card"><h2>Paid sales by date</h2>${Object.keys(byDay).length?`<div class="table-wrap"><table><thead><tr><th>Date</th><th>Paid sales</th></tr></thead><tbody>${Object.entries(byDay).map(([d,n])=>`<tr><td>${esc(d)}</td><td>${money(n)}</td></tr>`).join("")}</tbody></table></div>`:`<div class="empty-table">Paid orders will appear here.</div>`}</section>`);}
  function adminView(){if(!isAuthed())return adminLogin();if(!state.apiConnected)return adminLayout(`<section class="error-state"><h2>Google Sheets unavailable</h2><p>${esc(state.error||"Admin data could not be loaded.")}</p><div class="panel-actions" style="justify-content:center"><button class="button secondary" data-action="logout">SIGN OUT</button><button class="button" data-action="reload">TRY AGAIN</button></div></section>`);const path=location.pathname;if(path==="/admin/products")return productsPage();if(path==="/admin/orders")return ordersPage();if(path==="/admin/stock")return stockPage();if(path==="/admin/reports")return reportsPage();return dashboard();}
  function render(){document.title=isAdmin()?"Samson Cafe · Admin":"Samson Cafe — Good Coffee. Good Food. Good Moments.";if(location.pathname==="/admin/login"){root.innerHTML=adminLogin();return;}root.innerHTML=isAdmin()?adminView():(state.selected?checkoutView():state.confirmed?successView(state.confirmed):menuView());}
  async function refresh(){try{const ps=await getPublicItems();state.products=(Array.isArray(ps)?ps:ps.items||[]).map(normalizeProduct);state.error="";state.apiConnected=true;if(isAuthed()){try{state.orders=await fetchOrders();localStorage.setItem(ORDERS_CACHE_KEY,JSON.stringify(state.orders));}catch(e){/* Keep the last locally cached orders when the API is unavailable. */}}}catch(e){state.apiConnected=false;state.error=API_URL?"We couldn't load the cafe data. Check the Apps Script deployment and try again.":"Google Apps Script is not configured. Set GOOGLE_SCRIPT_URL in config.js to load the live menu.";state.products=[];}render();}
  async function login(password){if(password!=="admin1234"){state.error="Incorrect admin password.";render();return;}sessionStorage.setItem("samson_admin_token","local-admin-session");state.error="";navigate("/admin");await refresh();}
  function customerValid(){const c=state.customer;if(!c.name?.trim()||!/^\+?[0-9\s()-]{8,16}$/.test(c.phone||"")||!/^\S+@\S+\.\S+$/.test(c.email||"")){toast("Please enter a name, valid phone number, and email.",true);return false;}if(state.orderType==="Delivery"&&(!c.address?.trim()||!/^\d{6}$/.test(c.pincode||""))){toast("Please enter a delivery address and 6-digit pincode.",true);return false;}return true;}
  async function placeOrder(){if(state.busy)return;const p=state.selected;if(!p||state.quantity<1||state.quantity>p.stock){state.error="Sorry, this item is currently out of stock.";render();return;}state.busy=true;state.error="";render();try{const response=await postApi({action:"placeOrder",itemId:p.id,quantity:state.quantity});const order=normalizeOrder(response.order||response);state.orders=[order,...state.orders.filter(existing=>existing.id!==order.id)];localStorage.setItem(ORDERS_CACHE_KEY,JSON.stringify(state.orders));state.products=state.products.map(x=>x.id===p.id?{...x,stock:Number(response.order?.stockRemaining??(x.stock-state.quantity))}:x);state.confirmed={...order,product:p};state.selected=null;state.busy=false;render();}catch(e){state.busy=false;state.error="Unable to place your order. Please check Apps Script access and item availability, then try again.";render();}}
  function modal(title,body,saveLabel,onSave){const cover=document.createElement("div");cover.className="modal-backdrop";cover.innerHTML=`<div class="modal" role="dialog" aria-modal="true"><div class="modal-head"><h2>${title}</h2><button class="icon-button" data-close aria-label="Close">×</button></div>${body}<div class="modal-actions"><button class="admin-button light" data-close>CANCEL</button><button class="admin-button" data-save>${saveLabel}</button></div></div>`;document.body.appendChild(cover);cover.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>cover.remove());cover.addEventListener("click",e=>{if(e.target===cover)cover.remove();});cover.querySelector("[data-save]").onclick=async()=>{const form=cover.querySelector("form");if(form&&!form.reportValidity())return;await onSave(cover);};return cover;}
  function productModal(product){const p=product||{name:"",image:"",stock:0,price:""};modal(product?"Edit product":"Add a menu item",`<form id="product-form"><div class="form-grid"><div class="field wide"><label>Product name</label><input name="name" required maxlength="80" value="${esc(p.name)}"></div><div class="field wide"><label>Image URL</label><input name="image" type="url" value="${esc(p.image)}" placeholder="https://…"></div><div class="field"><label>Stock</label><input name="stock" type="number" min="0" step="1" required value="${p.stock}"></div><div class="field"><label>Price (₹)</label><input name="price" type="number" min="0.01" step="0.01" required value="${p.price}"></div></div></form>`,product?"SAVE CHANGES":"ADD PRODUCT",async box=>{const button=box.querySelector("[data-save]"),f=new FormData(box.querySelector("form"));const data={name:String(f.get("name")).trim(),image:String(f.get("image")).trim(),stock:Number(f.get("stock")),price:Number(f.get("price"))};button.disabled=true;button.textContent="SAVING…";try{await apiAdmin(product?"updateProduct":"createProduct",product?{...data,id:product.id}:{...data});box.remove();await refresh();toast(product?"Product updated.":"Product added.");}catch(e){button.disabled=false;button.textContent=product?"SAVE CHANGES":"ADD PRODUCT";toast("Couldn't save this product. Please try again.",true);}});}
  function stockModal(product){const box=modal("Update stock",`<form><div class="field"><label>Current stock · ${esc(product.name)}</label><input name="stock" type="number" min="0" step="1" required value="${product.stock}"></div></form>`,"SAVE STOCK",async modalBox=>{const button=modalBox.querySelector("[data-save]"),stock=Number(new FormData(modalBox.querySelector("form")).get("stock"));button.disabled=true;button.textContent="SAVING…";try{await apiAdmin("updateStock",{id:product.id,stock});modalBox.remove();await refresh();toast("Stock updated.");}catch(e){button.disabled=false;button.textContent="SAVE STOCK";toast("Couldn't update stock. Please try again.",true);}});}
  function orderDetails(order){modal("Order details",`<div class="details-grid"><div><small>Order ID</small><strong>${esc(order.id)}</strong></div><div><small>Item ID</small><strong>${esc(order.itemId)}</strong></div><div><small>Product</small><strong>${esc(orderItemName(order))}</strong></div><div><small>Quantity</small><strong>${order.quantity}</strong></div><div><small>Total amount</small><strong>${money(order.total)}</strong></div><div><small>Date and time</small><strong>${esc(formatDate(order.date))}</strong></div><div><small>Payment status</small><span class="badge ${order.status.toLowerCase()}">${esc(order.status)}</span></div></div><div style="margin-top:20px"><button class="admin-button" data-payment>${order.status==="Paid"?"MARK PENDING":"MARK PAID"}</button></div>`,"CLOSE",async box=>box.remove()).querySelector("[data-payment]").onclick=async()=>{const paymentStatus=order.status==="Paid"?"Pending":"Paid";try{state.orders=await updatePaymentRemote(order,paymentStatus);localStorage.setItem(ORDERS_CACHE_KEY,JSON.stringify(state.orders));document.querySelector(".modal-backdrop")?.remove();render();toast(`Payment marked ${paymentStatus.toLowerCase()}.`);}catch(e){toast("Couldn't update payment. Check Apps Script access and try again.",true);}};}
  root.addEventListener("click",async e=>{
    const nav=e.target.closest("[data-nav]");if(nav){e.preventDefault();navigate(nav.dataset.nav);return;}
    const buy=e.target.closest("[data-buy]");if(buy){const p=state.products.find(x=>x.id===buy.dataset.buy);if(!p||p.stock<1){toast("Sorry, this item is currently out of stock.",true);return;}state.selected=p;state.quantity=1;state.step=1;state.customer={};state.error="";state.confirmed=null;render();window.scrollTo(0,0);return;}
    const details=e.target.closest("[data-order-details]");if(details){const o=state.orders.find(x=>x.id===details.dataset.orderDetails);if(o)orderDetails(o);return;}
    const edit=e.target.closest("[data-edit]");if(edit){const p=state.products.find(x=>x.id===edit.dataset.edit);if(p)productModal(p);return;}
    const stock=e.target.closest("[data-stock]");if(stock){const p=state.products.find(x=>x.id===stock.dataset.stock);if(p)stockModal(p);return;}
    const toggle=e.target.closest("[data-toggle]");if(toggle){const p=state.products.find(x=>x.id===toggle.dataset.toggle);if(!p)return;try{await apiAdmin("updateProduct",{id:p.id,enabled:!p.enabled});await refresh();toast(`Product ${p.enabled?"disabled":"enabled"}.`);}catch(err){toast("Couldn't update this product.",true);}return;}
    const a=e.target.closest("[data-action]")?.dataset.action;if(!a)return;
    if(a==="back-menu"){state.selected=null;state.confirmed=null;state.step=1;state.error="";render();return;}
    if(a==="minus"){state.quantity=Math.max(1,state.quantity-1);render();return;}
    if(a==="plus"){if(state.quantity<state.selected.stock)state.quantity++;render();return;}
    if(a==="step1"){state.step=1;state.error="";render();return;}
    if(a==="step2"){if(state.quantity<1||state.quantity>state.selected.stock){state.error="Please select a valid quantity.";render();return;}state.step=2;render();return;}
    if(a==="save-details"){const c={...state.customer,name:$("#customer-name")?.value||"",phone:$("#customer-phone")?.value||"",email:$("#customer-email")?.value||"",address:$("#address")?.value||"",landmark:$("#landmark")?.value||"",pincode:$("#pincode")?.value||"",note:$("#note")?.value||""};state.customer=c;if(!customerValid())return;state.step=3;render();return;}
    if(a==="place"){await placeOrder();return;}
    if(a==="refresh-orders"){const button=e.target.closest("[data-action=refresh-orders]");if(button){button.disabled=true;button.textContent="REFRESHING…";}await refresh();return;}
    if(a==="reload"){state.error="";await refresh();return;}
    if(a==="add-product"){productModal(null);return;}
    if(a==="logout"){sessionStorage.removeItem("samson_admin_token");state.orders=[];navigate("/admin/login");return;}
  });
  root.addEventListener("change",e=>{if(e.target.name==="order-type"){state.orderType=e.target.value;render();}if(e.target.dataset.filter)applyFilters();});
  root.addEventListener("input",e=>{if(e.target.matches("[data-search]"))applyFilters();});
  function applyFilters(){const path=location.pathname;const q=$("[data-search]")?.value.toLowerCase()||"";if(path==="/admin/products"){let rows=state.products.filter(p=>`${p.name} ${p.id}`.toLowerCase().includes(q));const f=$("[data-filter=product-stock]")?.value;if(f==="low")rows=rows.filter(p=>p.stock>0&&p.stock<=Number(C.LOW_STOCK_THRESHOLD||10));if(f==="out")rows=rows.filter(p=>p.stock===0);const el=$("#products-table");if(el)el.innerHTML=productsTable(rows);}if(path==="/admin/stock"){let rows=state.products.filter(p=>`${p.name} ${p.id}`.toLowerCase().includes(q));const f=$("[data-filter=stock-level]")?.value;if(f==="out")rows=rows.filter(p=>p.stock===0);if(f==="low")rows=rows.filter(p=>p.stock>0&&p.stock<=Number(C.LOW_STOCK_THRESHOLD||10));if(f==="in")rows=rows.filter(p=>p.stock>Number(C.LOW_STOCK_THRESHOLD||10));const el=$("#stock-table");if(el)el.innerHTML=stockTable(rows);}if(path==="/admin/orders"){let rows=state.orders.filter(o=>`${o.id} ${o.itemId} ${orderItemName(o)}`.toLowerCase().includes(q));const s=$("[data-filter=status]")?.value,d=$("[data-filter=date]")?.value,sort=$("[data-filter=sort]")?.value;if(s)rows=rows.filter(o=>o.status===s);if(d)rows=rows.filter(o=>new Date(o.date).toISOString().slice(0,10)===d);rows.sort((a,b)=>(new Date(a.date)-new Date(b.date))*(sort==="oldest"?1:-1));const el=$("#orders-table");if(el)el.innerHTML=ordersTable(rows);}}
  root.addEventListener("submit",e=>{if(e.target.id==="login-form"){e.preventDefault();login($("#admin-password").value);}});
  render();
  if(isAdmin()&&location.pathname!=="/admin/login"&&!isAuthed())navigate("/admin/login");
  refresh();
  window.setInterval(()=>{if(isAuthed())refresh();},60000);
})();
