/** Samson Cafe Sheets API. Existing Items and Orders columns stay unchanged.
 * Script Properties: SPREADSHEET_ID (optional; defaults to the cafe spreadsheet below), SAMSON_ADMIN_PASSWORD (optional; defaults to admin1234).
 * Deploy as a Web App, execute as you, accessible to anyone.
 */
const ITEMS_SHEET='Items', ORDERS_SHEET='Orders', TOKEN_TTL_SECONDS=21600;
function doGet(e){const q=e&&e.parameter||{};let p={};try{if(q.payload)p=JSON.parse(q.payload);Object.keys(q).forEach(k=>{if(!['action','callback','payload'].includes(k))p[k]=q[k];});return respond_(e,{ok:true,data:dispatch_(String(q.action||''),p)});}catch(err){return respond_(e,{ok:false,message:safeMessage_(err)});}}
function dispatch_(a,p){switch(a){case'getProducts':return getProducts_();case'adminChallenge':return adminChallenge_();case'adminLogin':return adminLogin_(p.nonce,p.proof);case'getOrders':requireAdmin_(p.adminToken);return getOrders_();case'placeOrder':return createOrder_(p);case'createProduct':requireAdmin_(p.adminToken);return createProduct_(p);case'updateProduct':requireAdmin_(p.adminToken);return updateProduct_(p);case'updateStock':requireAdmin_(p.adminToken);return updateStock_(p);case'updatePayment':requireAdmin_(p.adminToken);return updatePayment_(p);default:throw Error('Unknown API action.');}}
function spreadsheet_(){const id=PropertiesService.getScriptProperties().getProperty('SPREADSHEET_ID')||'1vDEiG_-KM4rfdb9cb6UPzE86BieHmtHKhLivOLVX61w';return SpreadsheetApp.openById(id);}
function sheet_(n,min){const s=spreadsheet_().getSheetByName(n);if(!s)throw Error('Required sheet is missing: '+n);if(s.getMaxColumns()<min)throw Error('Sheet structure does not match: '+n);return s;}
function getProducts_(){const s=sheet_(ITEMS_SHEET,5),n=s.getLastRow();if(n<2)return[];const d=disabledIds_();return s.getRange(2,1,n-1,5).getValues().filter(r=>r[0]!=='').map(r=>({id:String(r[0]),name:String(r[1]),image:String(r[2]||''),stock:Number(r[3])||0,price:Number(r[4])||0,enabled:!d[String(r[0])] }));}
function getOrders_(){const s=sheet_(ORDERS_SHEET,6),n=s.getLastRow();if(n<2)return[];return s.getRange(2,1,n-1,6).getValues().filter(r=>r[0]!=='').map(r=>({id:String(r[0]),itemId:String(r[1]),quantity:Number(r[2])||0,total:Number(r[3])||0,date:r[4] instanceof Date?r[4].toISOString():String(r[4]),status:String(r[5]||'Pending')})).reverse();}
function createOrder_(p){const id=String(p.itemId||'').trim(),qty=Number(p.quantity);if(!id||!Number.isInteger(qty)||qty<1)throw Error('Invalid order quantity.');const lock=LockService.getScriptLock();lock.waitLock(20000);try{const items=sheet_(ITEMS_SHEET,5),orders=sheet_(ORDERS_SHEET,6),rows=items.getLastRow()<2?[]:items.getRange(2,1,items.getLastRow()-1,5).getValues(),i=rows.findIndex(r=>String(r[0])===id);if(i<0||disabledIds_()[id])throw Error('This product is unavailable.');const stock=Number(rows[i][3])||0,price=Number(rows[i][4])||0;if(stock<qty)throw Error('There is not enough stock for this order.');if(price<=0)throw Error('This product price is not valid.');const orderId=nextOrderId_(orders),now=new Date(),total=price*qty,row=Math.max(orders.getLastRow()+1,2);orders.getRange(row,1,1,6).setValues([[orderId,id,qty,total,now,'Pending']]);try{items.getRange(i+2,4).setValue(stock-qty);SpreadsheetApp.flush();}catch(err){orders.deleteRow(row);throw err;}return{id:orderId,itemId:id,quantity:qty,total:total,date:now.toISOString(),status:'Pending'};}finally{lock.releaseLock();}}
function nextOrderId_(s){const n=s.getLastRow(),ids=n<2?[]:s.getRange(2,1,n-1,1).getValues().map(r=>String(r[0]||'')),max=ids.reduce((m,id)=>{const x=id.match(/^ORD(\d+)$/i);return x?Math.max(m,Number(x[1])):m;},0);return'ORD'+String(max+1).padStart(3,'0');}
function nextItemId_(rows){let m=rows.reduce((v,r)=>{const x=String(r[0]||'').match(/^C(\d+)$/i);return x?Math.max(v,Number(x[1])):v;},0),id;do{id='C'+String(++m).padStart(3,'0');}while(rows.some(r=>String(r[0])===id));return id;}
function createProduct_(p){const name=String(p.name||'').trim(),image=String(p.image||'').trim(),stock=Number(p.stock),price=Number(p.price);if(!name||!Number.isInteger(stock)||stock<0||!Number.isFinite(price)||price<=0)throw Error('Product details are invalid.');const lock=LockService.getScriptLock();lock.waitLock(20000);try{const s=sheet_(ITEMS_SHEET,5),n=s.getLastRow(),rows=n<2?[]:s.getRange(2,1,n-1,5).getValues(),id=nextItemId_(rows);s.getRange(Math.max(n+1,2),1,1,5).setValues([[id,name,image,stock,price]]);return{id:id,name:name,image:image,stock:stock,price:price,enabled:true};}finally{lock.releaseLock();}}
function updateProduct_(p){const id=String(p.id||'').trim();if(!id)throw Error('Product ID is required.');const lock=LockService.getScriptLock();lock.waitLock(20000);try{const s=sheet_(ITEMS_SHEET,5),n=s.getLastRow();if(n<2)throw Error('Product not found.');const rows=s.getRange(2,1,n-1,5).getValues(),i=rows.findIndex(r=>String(r[0])===id);if(i<0)throw Error('Product not found.');const r=rows[i];if(p.name!==undefined){const v=String(p.name).trim();if(!v)throw Error('Product name is required.');r[1]=v;}if(p.image!==undefined)r[2]=String(p.image).trim();if(p.stock!==undefined){const v=Number(p.stock);if(!Number.isInteger(v)||v<0)throw Error('Stock must be zero or more.');r[3]=v;}if(p.price!==undefined){const v=Number(p.price);if(!Number.isFinite(v)||v<=0)throw Error('Price must be greater than zero.');r[4]=v;}s.getRange(i+2,1,1,5).setValues([r]);if(p.enabled!==undefined)setEnabled_(id,p.enabled===true||p.enabled==='true');return{id:String(r[0]),name:String(r[1]),image:String(r[2]||''),stock:Number(r[3]),price:Number(r[4]),enabled:!disabledIds_()[id]};}finally{lock.releaseLock();}}
function updateStock_(p){const stock=Number(p.stock);if(!Number.isInteger(stock)||stock<0)throw Error('Stock must be zero or more.');return updateProduct_({id:p.id,stock:stock});}
function updatePayment_(p){const id=String(p.orderId||'').trim(),status=String(p.status||'');if(!id||!['Pending','Paid'].includes(status))throw Error('Payment status is invalid.');const s=sheet_(ORDERS_SHEET,6),n=s.getLastRow();if(n<2)throw Error('Order not found.');const ids=s.getRange(2,1,n-1,1).getValues(),i=ids.findIndex(r=>String(r[0])===id);if(i<0)throw Error('Order not found.');s.getRange(i+2,6).setValue(status);return{id:id,status:status};}
function adminChallenge_(){const nonce=Utilities.getUuid()+Utilities.getUuid();CacheService.getScriptCache().put('login:'+nonce,'1',120);return{nonce:nonce};}
function adminLogin_(nonce,proof){const cache=CacheService.getScriptCache(),key='login:'+String(nonce||'');if(!nonce||!proof||cache.get(key)!=='1')throw Error('Invalid admin credentials.');cache.remove(key);const password=PropertiesService.getScriptProperties().getProperty('SAMSON_ADMIN_PASSWORD')||'admin1234';const passwordHash=sha256_(password),expected=sha256_(String(nonce)+passwordHash);if(!constantTimeEqual_(expected,String(proof)))throw Error('Invalid admin credentials.');const token=Utilities.getUuid()+Utilities.getUuid();cache.put('admin:'+token,'1',TOKEN_TTL_SECONDS);return{token:token};}
function sha256_(value){return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(value),Utilities.Charset.UTF_8).map(b=>(b<0?b+256:b).toString(16).padStart(2,'0')).join('');}
function constantTimeEqual_(a,b){if(a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i++)diff|=a.charCodeAt(i)^b.charCodeAt(i);return diff===0;}
function requireAdmin_(token){if(!token||CacheService.getScriptCache().get('admin:'+String(token))!=='1')throw Error('Admin session expired. Sign in again.');}
function disabledIds_(){return JSON.parse(PropertiesService.getScriptProperties().getProperty('SAMSON_DISABLED_ITEMS')||'{}');}
function setEnabled_(id,enabled){const d=disabledIds_();if(enabled)delete d[id];else d[id]=true;PropertiesService.getScriptProperties().setProperty('SAMSON_DISABLED_ITEMS',JSON.stringify(d));}
function respond_(e,result){const cb=e&&e.parameter&&String(e.parameter.callback||''),json=JSON.stringify(result);if(cb&&/^[A-Za-z_$][\w$]*$/.test(cb))return ContentService.createTextOutput(cb+'('+json+');').setMimeType(ContentService.MimeType.JAVASCRIPT);return ContentService.createTextOutput(json).setMimeType(ContentService.MimeType.JSON);}
function safeMessage_(err){const t=err&&err.message?String(err.message):'Request failed.';return t.length>180?'Request failed.':t;}
